"""add_paint_module_and_car_size

Revision ID: 6c03ecfc53c1
Revises: 942703975bd5
Create Date: 2026-01-19 11:22:58.448772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6c03ecfc53c1'
down_revision: Union[str, Sequence[str], None] = '942703975bd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paintconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price_per_cm2', sa.Float(), nullable=False),
    sa.Column('min_margin_percent', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehiclesizearea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.Enum('SMALL', 'MEDIUM', 'LARGE', 'EXTRA_LARGE', name='vehiclesize'), nullable=False),
    sa.Column('area_cm2', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('size')
    )
    op.create_table('paintjob',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('income_id', sa.Integer(), nullable=False),
    sa.Column('paint_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('negotiated_price', sa.Float(), nullable=False),
    sa.Column('margin_percent', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['income_id'], ['income.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cars', sa.Column('size', sa.Enum('SMALL', 'MEDIUM', 'LARGE', 'EXTRA_LARGE', name='vehiclesize'), nullable=False))
    
    # Agregar valor 'FINISHED' al tipo enum 'photocategory' en PostgreSQL
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("COMMIT")
        op.execute("ALTER TYPE photocategory ADD VALUE IF NOT EXISTS 'FINISHED'")

    op.alter_column('photos', 'category',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('ENTRY', 'PROCESS', 'FINISHED', 'EXIT', name='photocategory'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photos', 'category',
               existing_type=sa.Enum('ENTRY', 'PROCESS', 'FINISHED', 'EXIT', name='photocategory'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
    op.drop_column('cars', 'size')
    op.drop_table('paintjob')
    op.drop_table('vehiclesizearea')
    op.drop_table('paintconfig')
    # ### end Alembic commands ###
