"""add target margin to paintconfig

Revision ID: ebb1dd5d60fd
Revises: e5b6be238683
Create Date: 2026-06-30 16:54:27.556740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ebb1dd5d60fd'
down_revision: Union[str, Sequence[str], None] = 'e5b6be238683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paintconfig', sa.Column('target_margin_percent', sa.Float(), server_default='40.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paintconfig', 'target_margin_percent')
    # ### end Alembic commands ###
