/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedPaintIndexRouteImport } from './routes/_authenticated/paint/index'
import { Route as AuthenticatedIncomeIndexRouteImport } from './routes/_authenticated/income/index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients/index'
import { Route as AuthenticatedCarsIndexRouteImport } from './routes/_authenticated/cars/index'
import { Route as AuthenticatedClientsClientIdRouteImport } from './routes/_authenticated/clients/$clientId'
import { Route as AuthenticatedCarsCarsIdRouteImport } from './routes/_authenticated/cars/$carsId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPaintIndexRoute = AuthenticatedPaintIndexRouteImport.update({
  id: '/paint/',
  path: '/paint/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIncomeIndexRoute =
  AuthenticatedIncomeIndexRouteImport.update({
    id: '/income/',
    path: '/income/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCarsIndexRoute = AuthenticatedCarsIndexRouteImport.update({
  id: '/cars/',
  path: '/cars/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientsClientIdRoute =
  AuthenticatedClientsClientIdRouteImport.update({
    id: '/clients/$clientId',
    path: '/clients/$clientId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCarsCarsIdRoute = AuthenticatedCarsCarsIdRouteImport.update({
  id: '/cars/$carsId',
  path: '/cars/$carsId',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/cars/$carsId': typeof AuthenticatedCarsCarsIdRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/cars/': typeof AuthenticatedCarsIndexRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/income/': typeof AuthenticatedIncomeIndexRoute
  '/paint/': typeof AuthenticatedPaintIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/cars/$carsId': typeof AuthenticatedCarsCarsIdRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/cars': typeof AuthenticatedCarsIndexRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/income': typeof AuthenticatedIncomeIndexRoute
  '/paint': typeof AuthenticatedPaintIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/cars/$carsId': typeof AuthenticatedCarsCarsIdRoute
  '/_authenticated/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/_authenticated/cars/': typeof AuthenticatedCarsIndexRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/income/': typeof AuthenticatedIncomeIndexRoute
  '/_authenticated/paint/': typeof AuthenticatedPaintIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/cars/$carsId'
    | '/clients/$clientId'
    | '/cars/'
    | '/clients/'
    | '/income/'
    | '/paint/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/cars/$carsId'
    | '/clients/$clientId'
    | '/cars'
    | '/clients'
    | '/income'
    | '/paint'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/cars/$carsId'
    | '/_authenticated/clients/$clientId'
    | '/_authenticated/cars/'
    | '/_authenticated/clients/'
    | '/_authenticated/income/'
    | '/_authenticated/paint/'
    | '/_authenticated/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/paint/': {
      id: '/_authenticated/paint/'
      path: '/paint'
      fullPath: '/paint/'
      preLoaderRoute: typeof AuthenticatedPaintIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/income/': {
      id: '/_authenticated/income/'
      path: '/income'
      fullPath: '/income/'
      preLoaderRoute: typeof AuthenticatedIncomeIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cars/': {
      id: '/_authenticated/cars/'
      path: '/cars'
      fullPath: '/cars/'
      preLoaderRoute: typeof AuthenticatedCarsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/$clientId': {
      id: '/_authenticated/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cars/$carsId': {
      id: '/_authenticated/cars/$carsId'
      path: '/cars/$carsId'
      fullPath: '/cars/$carsId'
      preLoaderRoute: typeof AuthenticatedCarsCarsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedCarsCarsIdRoute: typeof AuthenticatedCarsCarsIdRoute
  AuthenticatedClientsClientIdRoute: typeof AuthenticatedClientsClientIdRoute
  AuthenticatedCarsIndexRoute: typeof AuthenticatedCarsIndexRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedIncomeIndexRoute: typeof AuthenticatedIncomeIndexRoute
  AuthenticatedPaintIndexRoute: typeof AuthenticatedPaintIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedCarsCarsIdRoute: AuthenticatedCarsCarsIdRoute,
  AuthenticatedClientsClientIdRoute: AuthenticatedClientsClientIdRoute,
  AuthenticatedCarsIndexRoute: AuthenticatedCarsIndexRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedIncomeIndexRoute: AuthenticatedIncomeIndexRoute,
  AuthenticatedPaintIndexRoute: AuthenticatedPaintIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
